rootdir:=..
src:=should.ml trap.ml
ocflags:=-opaque
bin:=trap.exe
cmm:=camlTrap__main_273 camlTrap__maybe_raise_269
linear:=camlTrap__main_273 camlTrap__maybe_raise_269
dump:=camlTrap__main_273 camlTrap__maybe_raise_269

include ../Makefile.mk
