rootdir:=..
src:=should.mli should.ml nested.ml
ocflags:=-opaque
bin:=nested.exe
cmm:=camlNested__probably_raise_351
linear:=camlNested__probably_raise_351
dump:=camlNested__main_359 camlNested__maybe_raise_355 camlNested__probably_raise_351 camlNested__definitely_raise_347

include ../Makefile.mk
