rootdir:=..
src:=notrace.ml
ocflags:=-g
bin:=notrace.exe
cmm:=camlNotrace__all_somes_327 camlNotrace__fun_347
dump:=camlNotrace__all_somes_327 camlNotrace__fun_347
ocamlrunparam=b

include ../Makefile.mk
