rootdir:=..
src:=should.ml raise.ml
ocflags:=-opaque
bin:=raise.exe
cmm:=camlRaise__main_273 camlRaise__maybe_raise_269
linear:=camlRaise__main_273 camlRaise__maybe_raise_269
dump:=camlRaise__main_273 camlRaise__maybe_raise_269

include ../Makefile.mk
