rootdir:=..
src:=should.ml noraise.ml
ocflags:=-opaque
bin:=noraise.exe
cmm:=camlNoraise__main_273 camlNoraise__maybe_raise_269
linear:=camlNoraise__main_273
dump:=camlNoraise__main_273 camlNoraise__maybe_raise_269

include ../Makefile.mk
