rootdir:=..
src:=should.mli should.ml backtrace.ml
ocflags:=-opaque -g
bin:=backtrace.exe
cmm:=camlBacktrace__main_359 camlBacktrace__probably_raise_351 camlBacktrace__definitely_raise_347
dump:=camlBacktrace__main_359 camlBacktrace__probably_raise_351 camlBacktrace__definitely_raise_347
ocamlrunparam=b

include ../Makefile.mk
